"""Add additional fields to FavoriteMovie model

Revision ID: 217019ea64ae
Revises: 
Create Date: 2025-04-09 11:36:38.079054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217019ea64ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_path', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('vote_average', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('overview', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('watch_later', schema=None) as batch_op:
        batch_op.alter_column('movie_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint('unique_user_movie_watch_later', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_later', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_movie_watch_later', ['user_id', 'movie_id'])
        batch_op.alter_column('movie_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    with op.batch_alter_table('favorite_movie', schema=None) as batch_op:
        batch_op.drop_column('overview')
        batch_op.drop_column('vote_average')
        batch_op.drop_column('release_date')
        batch_op.drop_column('poster_path')

    # ### end Alembic commands ###
